# "numpy" study

In [4]:
import numpy as np

a = np.array([[1,2,3],
              [3,2,1]])

print ("number of dimensions",a.ndim)
print ("shape",a.shape)
print ("data type",a.dtype)


number of dimensions 2
shape (2, 3)
data type int32


In [7]:
a = np.zeros((2,3,2))

print (a)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [8]:
np.ones_like(a)


array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [9]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0 , 1 , 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [14]:
np.random.seed(100) # when the seed is fixed it sets the initial state of the Python randon number generation algoritm
                    # so the random numbers will always be the same
                    # this helps in machine learinig model ... this way the results are predictable 
np.random.randint(1 , 10 , (3,4))


array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3]])

In [16]:
onedim_arr = np.array([1,2,3,4,5])

multidim_arr = np.repeat (onedim_arr,5)

print (multidim_arr)

[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 5 5 5 5 5]


In [19]:
#create a multi dimensional array based on a tile 'onedim_arr' ... and receive the size of the array (5,1)
multidim_arr = np.tile (onedim_arr,(5,1))
print (multidim_arr)


print (multidim_arr.T) #T = transpose

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]


In [27]:
arr1 = np.array([5,10,15,20])
print(arr1)

arr2 = np.arange(5,9)
print(arr2)

print(arr1 - arr2)

print(arr1 *2)

print("sum:",arr1.sum())

print("max:",arr1.max())

print("min:",arr1.min())

print("mean",arr1.mean())

print("median",np.median(arr1))



[ 5 10 15 20]
[5 6 7 8]
[ 0  4  8 12]
[10 20 30 40]
sum: 50
max: 20
min: 5
mean 12.5
median 12.5


In [29]:
tens = np.arange(0,120,10).reshape(3,4)

print(tens)

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [33]:
horizontal = np.array([-5,-10,-15,-20])

print (horizontal)


print ("->", tens + horizontal)

[ -5 -10 -15 -20]
-> [[-5  0  5 10]
 [35 40 45 50]
 [75 80 85 90]]


In [39]:
# axis = 0 column-wise operations ... down the rows
# axis = 1 row-wise operations ... across the colums

tens = np.arange(0,120,10).reshape(3,4)
print (tens)

# mean across colum
print ("Mean across column:",tens.mean(axis=0))

# mean across row
print ("Mean across row:",tens.mean(axis=1))

[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
Mean across column: [40. 50. 60. 70.]
Mean across row: [15. 55. 95.]


In [44]:

matrix1 = np.random.randint(1,11,12).reshape (3,4)

print ("m1:",matrix1)

matrix2 = matrix1

print ("m2:",matrix2)

matrix3 = matrix1.copy()

print ("m3:",matrix3)

m1: [[ 4  7  4  5]
 [ 8  7  4 10]
 [ 1  5  5  6]]
m2: [[ 4  7  4  5]
 [ 8  7  4 10]
 [ 1  5  5  6]]
m3: [[ 4  7  4  5]
 [ 8  7  4 10]
 [ 1  5  5  6]]


In [45]:
matrix2[0,0] = -10

print ("m1:",matrix1)

print ("m2:",matrix2)

print ("m3:",matrix3)

m1: [[-10   7   4   5]
 [  8   7   4  10]
 [  1   5   5   6]]
m2: [[-10   7   4   5]
 [  8   7   4  10]
 [  1   5   5   6]]
m3: [[ 4  7  4  5]
 [ 8  7  4 10]
 [ 1  5  5  6]]
